import type { Metadata } from 'next'
import { Inter, Fraunces, Barlow } from 'next/font/google'
import './globals.css'

//header
import { NavBar } from "../components/navbar";
//footer
import { Footer } from "../components/footer";

//const inter = Inter({ subsets: ['sans-serif'] });

const fraunces = Fraunces({subsets: ['latin'],weight: ["900"]});
const barlow = Barlow({subsets: ['latin'],weight: ["200", "700"]})

export const metadata: Metadata = {
  title: 'CoffeRoasters',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${fraunces.className} ${barlow.className}`}>
        

        
        <NavBar />
        {children}
        <Footer />
        
      </body>
    </html>
  )
}
